// src/data/foodDatabase.js

export const foodDatabase = [
    // FRUITS
    { name: "Pomme", calorie: 52, glucide: 14, lipide: 0.2, proteine: 0.3, category: "fruits" },
    { name: "Banane", calorie: 89, glucide: 23, lipide: 0.3, proteine: 1.1, category: "fruits" },
    { name: "Orange", calorie: 47, glucide: 12, lipide: 0.1, proteine: 0.9, category: "fruits" },
    { name: "Poire", calorie: 57, glucide: 15, lipide: 0.1, proteine: 0.4, category: "fruits" },
    { name: "Fraise", calorie: 32, glucide: 7.7, lipide: 0.3, proteine: 0.7, category: "fruits" },
    { name: "Cerise", calorie: 50, glucide: 12, lipide: 0.3, proteine: 1, category: "fruits" },
    { name: "Raisin", calorie: 69, glucide: 18, lipide: 0.2, proteine: 0.7, category: "fruits" },
    { name: "Pêche", calorie: 39, glucide: 9.5, lipide: 0.1, proteine: 0.9, category: "fruits" },
    { name: "Abricot", calorie: 48, glucide: 11, lipide: 0.4, proteine: 1.4, category: "fruits" },
    { name: "Kiwi", calorie: 61, glucide: 15, lipide: 0.5, proteine: 1.1, category: "fruits" },
    { name: "Ananas", calorie: 50, glucide: 13, lipide: 0.1, proteine: 0.5, category: "fruits" },
    { name: "Mangue", calorie: 60, glucide: 15, lipide: 0.4, proteine: 0.8, category: "fruits" },
    { name: "Melon", calorie: 34, glucide: 8, lipide: 0.2, proteine: 0.8, category: "fruits" },
    { name: "Pastèque", calorie: 30, glucide: 7.6, lipide: 0.2, proteine: 0.6, category: "fruits" },
    { name: "Avocat", calorie: 160, glucide: 8.5, lipide: 14.7, proteine: 2, category: "fruits" },
    { name: "Citron", calorie: 29, glucide: 9, lipide: 0.3, proteine: 1.1, category: "fruits" },
    { name: "Pamplemousse", calorie: 42, glucide: 11, lipide: 0.1, proteine: 0.8, category: "fruits" },
    { name: "Myrtille", calorie: 57, glucide: 14, lipide: 0.3, proteine: 0.7, category: "fruits" },
    { name: "Framboise", calorie: 52, glucide: 12, lipide: 0.7, proteine: 1.2, category: "fruits" },
    { name: "Mûre", calorie: 43, glucide: 9.6, lipide: 0.5, proteine: 1.4, category: "fruits" },
    { name: "Figue", calorie: 74, glucide: 19, lipide: 0.3, proteine: 0.8, category: "fruits" },
    { name: "Grenade", calorie: 83, glucide: 19, lipide: 1.2, proteine: 1.7, category: "fruits" },
    { name: "Noix de coco", calorie: 354, glucide: 15, lipide: 33, proteine: 3.3, category: "fruits" },
    { name: "Datte", calorie: 282, glucide: 75, lipide: 0.4, proteine: 2.5, category: "fruits" },
    { name: "Clémentine", calorie: 47, glucide: 12, lipide: 0.2, proteine: 0.9, category: "fruits" },
    { name: "Mandarine", calorie: 53, glucide: 13, lipide: 0.3, proteine: 0.8, category: "fruits" },
    { name: "Prune", calorie: 46, glucide: 11, lipide: 0.3, proteine: 0.7, category: "fruits" },
    { name: "Litchi", calorie: 66, glucide: 17, lipide: 0.4, proteine: 0.8, category: "fruits" },
    { name: "Kaki", calorie: 70, glucide: 18, lipide: 0.2, proteine: 0.6, category: "fruits" },
    { name: "Goyave", calorie: 68, glucide: 14, lipide: 0.9, proteine: 2.5, category: "fruits" },

    // LÉGUMES
    { name: "Carotte", calorie: 41, glucide: 9.6, lipide: 0.2, proteine: 0.9, category: "légumes" },
    { name: "Tomate", calorie: 18, glucide: 3.9, lipide: 0.2, proteine: 0.9, category: "légumes" },
    { name: "Concombre", calorie: 15, glucide: 3.6, lipide: 0.1, proteine: 0.7, category: "légumes" },
    { name: "Poivron rouge", calorie: 31, glucide: 6, lipide: 0.3, proteine: 1, category: "légumes" },
    { name: "Poivron vert", calorie: 20, glucide: 4.6, lipide: 0.2, proteine: 0.9, category: "légumes" },
    { name: "Oignon", calorie: 40, glucide: 9, lipide: 0.1, proteine: 1.1, category: "légumes" },
    { name: "Ail", calorie: 149, glucide: 33, lipide: 0.5, proteine: 6.4, category: "légumes" },
    { name: "Courgette", calorie: 17, glucide: 3.1, lipide: 0.3, proteine: 1.2, category: "légumes" },
    { name: "Aubergine", calorie: 25, glucide: 6, lipide: 0.2, proteine: 1, category: "légumes" },
    { name: "Brocoli", calorie: 34, glucide: 6.6, lipide: 0.4, proteine: 2.8, category: "légumes" },
    { name: "Chou-fleur", calorie: 25, glucide: 5, lipide: 0.3, proteine: 1.9, category: "légumes" },
    { name: "Épinard", calorie: 23, glucide: 3.6, lipide: 0.4, proteine: 2.9, category: "légumes" },
    { name: "Laitue", calorie: 15, glucide: 2.9, lipide: 0.2, proteine: 1.4, category: "légumes" },
    { name: "Champignon", calorie: 22, glucide: 3.3, lipide: 0.3, proteine: 3.1, category: "légumes" },
    { name: "Asperge", calorie: 20, glucide: 3.9, lipide: 0.1, proteine: 2.2, category: "légumes" },
    { name: "Haricot vert", calorie: 31, glucide: 7, lipide: 0.1, proteine: 1.8, category: "légumes" },
    { name: "Petit pois", calorie: 81, glucide: 14, lipide: 0.4, proteine: 5.4, category: "légumes" },
    { name: "Maïs", calorie: 86, glucide: 19, lipide: 1.2, proteine: 3.2, category: "légumes" },
    { name: "Pomme de terre", calorie: 77, glucide: 17, lipide: 0.1, proteine: 2, category: "légumes" },
    { name: "Patate douce", calorie: 86, glucide: 20, lipide: 0.1, proteine: 1.6, category: "légumes" },
    { name: "Betterave", calorie: 43, glucide: 10, lipide: 0.2, proteine: 1.6, category: "légumes" },
    { name: "Radis", calorie: 16, glucide: 3.4, lipide: 0.1, proteine: 0.7, category: "légumes" },
    { name: "Céleri", calorie: 16, glucide: 3, lipide: 0.2, proteine: 0.7, category: "légumes" },
    { name: "Potiron", calorie: 26, glucide: 6.5, lipide: 0.1, proteine: 1, category: "légumes" },
    { name: "Chou", calorie: 25, glucide: 5.8, lipide: 0.1, proteine: 1.3, category: "légumes" },
    { name: "Salade verte", calorie: 14, glucide: 2.8, lipide: 0.2, proteine: 1, category: "légumes" },
    { name: "Poireau", calorie: 31, glucide: 6, lipide: 0.3, proteine: 1.5, category: "légumes" },
    { name: "Navet", calorie: 28, glucide: 6, lipide: 0.1, proteine: 0.9, category: "légumes" },
    { name: "Chou de Bruxelles", calorie: 43, glucSWide: 9, lipide: 0.3, proteine: 3.4, category: "légumes" },
    { name: "Panais", calorie: 75, glucide: 18, lipide: 0.3, proteine: 1.2, category: "légumes" },

    // VIANDES ET POISSONS
    { name: "Poulet", calorie: 165, glucide: 0, lipide: 3.6, proteine: 31, category: "viandes" },
    { name: "Blanc de poulet", calorie: 114, glucide: 0, lipide: 1, proteine: 23, category: "viandes" },
    { name: "Bœuf", calorie: 271, glucide: 0, lipide: 19, proteine: 26, category: "viandes" },
    { name: "Bœuf haché", calorie: 250, glucide: 0, lipide: 20, proteine: 17, category: "viandes" },
    { name: "Porc", calorie: 242, glucide: 0, lipide: 14, proteine: 27, category: "viandes" },
    { name: "Filet de porc", calorie: 143, glucide: 0, lipide: 5, proteine: 26, category: "viandes" },
    { name: "Agneau", calorie: 294, glucide: 0, lipide: 21, proteine: 25, category: "viandes" },
    { name: "Veau", calorie: 172, glucide: 0, lipide: 8, proteine: 23, category: "viandes" },
    { name: "Dinde", calorie: 189, glucide: 0, lipide: 7, proteine: 29, category: "viandes" },
    { name: "Blanc de dinde", calorie: 104, glucide: 0, lipide: 1, proteine: 22, category: "viandes" },
    { name: "Lapin", calorie: 173, glucide: 0, lipide: 8, proteine: 25, category: "viandes" },
    { name: "Canard", calorie: 337, glucide: 0, lipide: 28, proteine: 19, category: "viandes" },
    { name: "Foie de veau", calorie: 140, glucide: 3.8, lipide: 4.7, proteine: 19, category: "viandes" },
    { name: "Jambon", calorie: 145, glucide: 1, lipide: 5, proteine: 21, category: "viandes" },
    { name: "Saucisson", calorie: 300, glucide: 1, lipide: 25, proteine: 15, category: "viandes" },
    { name: "Saucisse", calorie: 280, glucide: 2, lipide: 25, proteine: 12, category: "viandes" },
    { name: "Bacon", calorie: 541, glucide: 1.4, lipide: 42, proteine: 37, category: "viandes" },
    { name: "Saumon", calorie: 208, glucide: 0, lipide: 13, proteine: 20, category: "poissons" },
    { name: "Thon", calorie: 184, glucide: 0, lipide: 6, proteine: 30, category: "poissons" },
    { name: "Cabillaud", calorie: 82, glucide: 0, lipide: 0.7, proteine: 18, category: "poissons" },
    { name: "Maquereau", calorie: 205, glucide: 0, lipide: 14, proteine: 19, category: "poissons" },
    { name: "Sardine", calorie: 208, glucide: 0, lipide: 12, proteine: 24, category: "poissons" },
    { name: "Truite", calorie: 141, glucide: 0, lipide: 6, proteine: 20, category: "poissons" },
    { name: "Crevette", calorie: 99, glucide: 0.9, lipide: 1.3, proteine: 21, category: "poissons" },
    { name: "Moule", calorie: 86, glucide: 3.7, lipide: 2.2, proteine: 12, category: "poissons" },
    { name: "Huître", calorie: 69, glucide: 3.9, lipide: 2, proteine: 7, category: "poissons" },
    { name: "Calamar", calorie: 92, glucide: 3, lipide: 1.4, proteine: 16, category: "poissons" },
    { name: "Sole", calorie: 83, glucide: 0, lipide: 1.3, proteine: 17, category: "poissons" },
    { name: "Merlu", calorie: 90, glucide: 0, lipide: 2, proteine: 18, category: "poissons" },
    { name: "Colin", calorie: 85, glucide: 0, lipide: 0.8, proteine: 18, category: "poissons" },

    // PRODUITS LAITIERS
    { name: "Lait entier", calorie: 61, glucide: 4.8, lipide: 3.3, proteine: 3.2, category: "produits laitiers" },
    { name: "Lait demi-écrémé", calorie: 46, glucide: 4.8, lipide: 1.5, proteine: 3.3, category: "produits laitiers" },
    { name: "Lait écrémé", calorie: 34, glucide: 5, lipide: 0.1, proteine: 3.4, category: "produits laitiers" },
    { name: "Yaourt nature", calorie: 59, glucide: 4.7, lipide: 3.3, proteine: 3.5, category: "produits laitiers" },
    { name: "Yaourt grec", calorie: 97, glucide: 3.6, lipide: 5, proteine: 9, category: "produits laitiers" },
    { name: "Fromage blanc", calorie: 79, glucide: 3.8, lipide: 3.8, proteine: 7.9, category: "produits laitiers" },
    { name: "Crème fraîche", calorie: 345, glucide: 2.5, lipide: 37, proteine: 2.1, category: "produits laitiers" },
    { name: "Beurre", calorie: 717, glucide: 0.1, lipide: 81, proteine: 0.9, category: "produits laitiers" },
    { name: "Camembert", calorie: 300, glucide: 0.4, lipide: 24, proteine: 20, category: "produits laitiers" },
    { name: "Emmental", calorie: 380, glucide: 1.5, lipide: 29, proteine: 29, category: "produits laitiers" },
    { name: "Chèvre", calorie: 364, glucide: 2, lipide: 30, proteine: 22, category: "produits laitiers" },
    { name: "Roquefort", calorie: 369, glucide: 2, lipide: 32, proteine: 21, category: "produits laitiers" },
    { name: "Comté", calorie: 400, glucide: 1, lipide: 32, proteine: 28, category: "produits laitiers" },
    { name: "Parmesan", calorie: 431, glucide: 3.2, lipide: 29, proteine: 38, category: "produits laitiers" },
    { name: "Mozzarella", calorie: 280, glucide: 2.2, lipide: 22, proteine: 18, category: "produits laitiers" },
    { name: "Fromage frais", calorie: 98, glucide: 3, lipide: 7, proteine: 8, category: "produits laitiers" },
    { name: "Gouda", calorie: 356, glucide: 2, lipide: 27, proteine: 25, category: "produits laitiers" },
    { name: "Cheddar", calorie: 403, glucide: 1.3, lipide: 33, proteine: 25, category: "produits laitiers" },
    { name: "Feta", calorie: 264, glucide: 4, lipide: 21, proteine: 14, category: "produits laitiers" },
    { name: "Ricotta", calorie: 174, glucide: 3, lipide: 13, proteine: 11, category: "produits laitiers" },

    // FÉCULENTS ET CÉRÉALES
    { name: "Riz blanc", calorie: 365, glucide: 80, lipide: 0.7, proteine: 7, category: "féculents" },
    { name: "Riz complet", calorie: 360, glucide: 77, lipide: 2.9, proteine: 7.5, category: "féculents" },
    { name: "Pâtes", calorie: 355, glucide: 74, lipide: 1.1, proteine: 12, category: "féculents" },
    { name: "Pâtes complètes", calorie: 350, glucide: 72, lipide: 2, proteine: 13, category: "féculents" },
    { name: "Quinoa", calorie: 368, glucide: 64, lipide: 6, proteine: 14, category: "féculents" },
    { name: "Boulgour", calorie: 342, glucide: 76, lipide: 1.3, proteine: 12, category: "féculents" },
    { name: "Semoule", calorie: 360, glucide: 73, lipide: 1, proteine: 13, category: "féculents" },
    { name: "Pain blanc", calorie: 265, glucide: 49, lipide: 3.2, proteine: 9, category: "féculents" },
    { name: "Pain complet", calorie: 247, glucide: 41, lipide: 2.9, proteine: 13, category: "féculents" },
    { name: "Pain de seigle", calorie: 259, glucide: 48, lipide: 3.3, proteine: 8.5, category: "féculents" },
    { name: "Baguette", calorie: 255, glucide: 57, lipide: 2, proteine: 9, category: "féculents" },
    { name: "Croissant", calorie: 406, glucide: 45, lipide: 23, proteine: 8, category: "féculents" },
    { name: "Brioche", calorie: 353, glucide: 45, lipide: 17, proteine: 8.8, category: "féculents" },
    { name: "Muesli", calorie: 367, glucide: 66, lipide: 7, proteine: 11, category: "féculents" },
    { name: "Flocons d'avoine", calorie: 379, glucide: 67, lipide: 7, proteine: 13, category: "féculents" },
    { name: "Couscous", calorie: 376, glucide: 77, lipide: 0.6, proteine: 13, category: "féculents" },
    { name: "Lentilles", calorie: 353, glucide: 60, lipide: 1, proteine: 26, category: "féculents" },
    { name: "Haricots rouges", calorie: 333, glucide: 60, lipide: 1, proteine: 22, category: "féculents" },
    { name: "Pois chiches", calorie: 364, glucide: 61, lipide: 6, proteine: 19, category: "féculents" },
    { name: "Haricots blancs", calorie: 333, glucide: 60, lipide: 0.8, proteine: 23, category: "féculents" },
    { name: "Blé", calorie: 339, glucide: 71, lipide: 1.9, proteine: 12, category: "féculents" },
    { name: "Orge", calorie: 354, glucide: 73, lipide: 2.3, proteine: 12, category: "féculents" },
    { name: "Millet", calorie: 378, glucide: 73, lipide: 4.2, proteine: 11, category: "féculents" },
    { name: "Sarrasin", calorie: 343, glucide: 72, lipide: 3.4, proteine: 13, category: "féculents" },

    // SNACKS ET GÂTEAUX
    { name: "Chocolat noir", calorie: 546, glucide: 46, lipide: 31, proteine: 7.8, category: "snacks" },
    { name: "Chocolat au lait", calorie: 535, glucide: 58, lipide: 30, proteine: 6.1, category: "snacks" },
    { name: "Chips", calorie: 547, glucide: 50, lipide: 37, proteine: 6.5, category: "snacks" },
    { name: "Biscuit", calorie: 474, glucide: 70, lipide: 20, proteine: 6.3, category: "snacks" },
    { name: "Cookie", calorie: 502, glucide: 64, lipide: 25, proteine: 6, category: "snacks" },
    { name: "Muffin", calorie: 377, glucide: 55, lipide: 16, proteine: 6, category: "snacks" },
    { name: "Pain au chocolat", calorie: 410, glucide: 45, lipide: 23, proteine: 8.2, category: "snacks" },
    { name: "Crêpe", calorie: 232, glucide: 27, lipide: 12, proteine: 5.8, category: "snacks" },
    { name: "Gaufre", calorie: 291, glucide: 39, lipide: 14, proteine: 6.5, category: "snacks" },
    { name: "Pancake", calorie: 227, glucide: 28, lipide: 11, proteine: 5.9, category: "snacks" },
    { name: "Glace vanille", calorie: 207, glucide: 26, lipide: 11, proteine: 3.5, category: "snacks" },
    { name: "Sorbet citron", calorie: 125, glucide: 32, lipide: 0.2, proteine: 0.4, category: "snacks" },
    { name: "Barre céréalière", calorie: 400, glucide: 65, lipide: 12, proteine: 8, category: "snacks" },
    { name: "Bonbon", calorie: 394, glucide: 98, lipide: 0.2, proteine: 0, category: "snacks" },
    { name: "Chocolat blanc", calorie: 539, glucide: 59, lipide: 32, proteine: 6, category: "snacks" },

    // BOISSONS
    { name: "Eau", calorie: 0, glucide: 0, lipide: 0, proteine: 0, category: "boissons" },
    { name: "Café", calorie: 2, glucide: 0, lipide: 0, proteine: 0.1, category: "boissons" },
    { name: "Thé", calorie: 1, glucide: 0.2, lipide: 0, proteine: 0, category: "boissons" },
    { name: "Jus d'orange", calorie: 45, glucide: 10, lipide: 0.2, proteine: 0.7, category: "boissons" },
    { name: "Jus de pomme", calorie: 46, glucide: 11, lipide: 0.1, proteine: 0.1, category: "boissons" },
    { name: "Coca-cola", calorie: 42, glucide: 10.4, lipide: 0, proteine: 0, category: "boissons" },
    { name: "Vin rouge", calorie: 85, glucide: 2.6, lipide: 0, proteine: 0.1, category: "boissons" },
    { name: "Bière", calorie: 43, glucide: 3.6, lipide: 0, proteine: 0.5, category: "boissons" },
    { name: "Smoothie fruits", calorie: 65, glucide: 16, lipide: 0.3, proteine: 1, category: "boissons" },
    { name: "Lait d'amande", calorie: 24, glucide: 3, lipide: 1.1, proteine: 0.5, category: "boissons" },
    { name: "Lait de soja", calorie: 54, glucide: 6, lipide: 1.8, proteine: 3.3, category: "boissons" },
    { name: "Jus de raisin", calorie: 60, glucide: 15, lipide: 0.1, proteine: 0.4, category: "boissons" },
    { name: "Eau gazeuse", calorie: 0, glucide: 0, lipide: 0, proteine: 0, category: "boissons" },
    { name: "Limonade", calorie: 40, glucide: 10, lipide: 0, proteine: 0, category: "boissons" },

    // MATIÈRES GRASSES
    { name: "Huile d'olive", calorie: 884, glucide: 0, lipide: 100, proteine: 0, category: "matières grasses" },
    { name: "Huile de tournesol", calorie: 884, glucide: 0, lipide: 100, proteine: 0, category: "matières grasses" },
    { name: "Huile de colza", calorie: 884, glucide: 0, lipide: 100, proteine: 0, category: "matières grasses" },
    { name: "Noix", calorie: 654, glucide: 14, lipide: 65, proteine: 15, category: "matières grasses" },
    { name: "Amande", calorie: 579, glucide: 21, lipide: 50, proteine: 21, category: "matières grasses" },
    { name: "Noisette", calorie: 628, glucide: 17, lipide: 61, proteine: 15, category: "matières grasses" },
    { name: "Pistache", calorie: 560, glucide: 28, lipide: 45, proteine: 20, category: "matières grasses" },
    { name: "Cacahuète", calorie: 567, glucide: 16, lipide: 49, proteine: 26, category: "matières grasses" },
    { name: "Graines de chia", calorie: 486, glucide: 42, lipide: 31, proteine: 17, category: "matières grasses" },
    { name: "Graines de lin", calorie: 534, glucide: 29, lipide: 42, proteine: 18, category: "matières grasses" },
    { name: "Beurre de cacahuète", calorie: 588, glucide: 20, lipide: 50, proteine: 25, category: "matières grasses" },
    { name: "Margarine", calorie: 720, glucide: 0.5, lipide: 80, proteine: 0.2, category: "matières grasses" },
    { name: "Graines de tournesol", calorie: 584, glucide: 20, lipide: 51, proteine: 21, category: "matières grasses" },
    { name: "Huile de coco", calorie: 892, glucide: 0, lipide: 100, proteine: 0, category: "matières grasses" },

    // ŒUFS
    { name: "Œuf entier", calorie: 155, glucide: 1.1, lipide: 10.8, proteine: 12.6, category: "œufs" },
    { name: "Blanc d'œuf", calorie: 52, glucide: 0.7, lipide: 0.2, proteine: 11, category: "œufs" },
    { name: "Jaune d'œuf", calorie: 322, glucide: 0.4, lipide: 27, proteine: 16, category: "œufs" },

    // CONDIMENTS ET ÉPICES
    { name: "Sel", calorie: 0, glucide: 0, lipide: 0, proteine: 0, category: "condiments" },
    { name: "Poivre", calorie: 251, glucide: 64, lipide: 3.3, proteine: 10, category: "condiments" },
    { name: "Basilic", calorie: 23, glucide: 2.7, lipide: 0.6, proteine: 3.2, category: "condiments" },
    { name: "Persil", calorie: 36, glucide: 6, lipide: 0.8, proteine: 3, category: "condiments" },
    { name: "Thym", calorie: 276, glucide: 64, lipide: 7, proteine: 9, category: "condiments" },
    { name: "Curcuma", calorie: 312, glucide: 67, lipide: 3.3, proteine: 9.7, category: "condiments" },
    { name: "Cannelle", calorie: 247, glucide: 81, lipide: 1.2, proteine: 4, category: "condiments" },
    { name: "Moutarde", calorie: 165, glucide: 9, lipide: 11, proteine: 8, category: "condiments" },
    { name: "Ketchup", calorie: 112, glucide: 28, lipide: 0.2, proteine: 1.2, category: "condiments" },
    { name: "Mayonnaise", calorie: 680, glucide: 2, lipide: 75, proteine: 1, category: "condiments" },
    { name: "Vinaigre", calorie: 21, glucide: 0.9, lipide: 0, proteine: 0, category: "condiments" },
    { name: "Sauce soja", calorie: 53, glucide: 5, lipide: 0.6, proteine: 8, category: "condiments" },

    // AUTRES
    { name: "Miel", calorie: 304, glucide: 82, lipide: 0, proteine: 0.3, category: "autres" },
    { name: "Confiture", calorie: 272, glucide: 70, lipide: 0.2, proteine: 0.5, category: "autres" },
    { name: "Nutella", calorie: 539, glucide: 58, lipide: 31, proteine: 6, category: "autres" },
    { name: "Sucre blanc", calorie: 387, glucide: 100, lipide: 0, proteine: 0, category: "autres" },
    { name: "Sucre complet", calorie: 380, glucide: 98, lipide: 0, proteine: 0, category: "autres" },
    { name: "Sirop d'érable", calorie: 260, glucide: 67, lipide: 0, proteine: 0, category: "autres" },
    { name: "Farine blanche", calorie: 364, glucide: 76, lipide: 1, proteine: 10, category: "autres" },
    { name: "Farine complète", calorie: 340, glucide: 72, lipide: 1.9, proteine: 13, category: "autres" },
    { name: "Tofu", calorie: 76, glucide: 1.9, lipide: 4.2, proteine: 8, category: "autres" },
    { name: "Seitan", calorie: 370, glucide: 14, lipide: 2, proteine: 75, category: "autres" },
    { name: "Tempeh", calorie: 193, glucide: 9, lipide: 11, proteine: 19, category: "autres" },
    { name: "Levure chimique", calorie: 53, glucide: 13, lipide: 0, proteine: 0, category: "autres" },
    { name: "Pâte d'amande", calorie: 460, glucide: 47, lipide: 28, proteine: 9, category: "autres" }
];

export default foodDatabase;